In [3]:
import pandas as pd
import numpy as np
import xgboost as xgb
from xgboost import XGBClassifier

In [2]:
# pip install xgboost==1.7.5

Collecting xgboost==1.7.5
  Downloading xgboost-1.7.5-py3-none-win_amd64.whl.metadata (1.9 kB)
Requirement already satisfied: numpy in c:\users\administrator\anaconda3\lib\site-packages (from xgboost==1.7.5) (1.26.4)
Requirement already satisfied: scipy in c:\users\administrator\anaconda3\lib\site-packages (from xgboost==1.7.5) (1.13.1)
Downloading xgboost-1.7.5-py3-none-win_amd64.whl (70.9 MB)
   ---------------------------------------- 0.0/70.9 MB ? eta -:--:--
   - -------------------------------------- 2.4/70.9 MB 19.2 MB/s eta 0:00:04
   -- ------------------------------------- 4.5/70.9 MB 13.4 MB/s eta 0:00:05
   --- ------------------------------------ 5.5/70.9 MB 10.5 MB/s eta 0:00:07
   --- ------------------------------------ 6.6/70.9 MB 8.6 MB/s eta 0:00:08
   ---- ----------------------------------- 7.6/70.9 MB 7.6 MB/s eta 0:00:09
   ---- ----------------------------------- 8.4/70.9 MB 7.4 MB/s eta 0:00:09
   ----- ---------------------------------- 8.9/70.9 MB 6.4 MB/s eta 0:00:10
   ----- ---------------------------------- 9.2/70.9 MB 5.8 MB/s eta 0:00:11
   ----- ---------------------------------- 9.4/70.9 MB 5.4 MB/s eta 0:00:12
   ----- ---------------------------------- 10.0/70.9 MB 4.8 MB/s eta 0:00:13
   ----- ---------------------------------- 10.2/70.9 MB 4.7 MB/s eta 0:00:13
   ------ --------------------------------- 10.7/70.9 MB 4.4 MB/s eta 0:00:14
   ------ --------------------------------- 11.3/70.9 MB 4.3 MB/s eta 0:00:14
   ------ --------------------------------- 11.8/70.9 MB 4.2 MB/s eta 0:00:15
   ------- -------------------------------- 12.6/70.9 MB 4.1 MB/s eta 0:00:15
   ------- -------------------------------- 13.1/70.9 MB 4.0 MB/s eta 0:00:15
   ------- -------------------------------- 13.9/70.9 MB 4.0 MB/s eta 0:00:15
   -------- ------------------------------- 14.7/70.9 MB 4.0 MB/s eta 0:00:15
   -------- ------------------------------- 15.5/70.9 MB 4.0 MB/s eta 0:00:15
   --------- ------------------------------ 16.3/70.9 MB 4.0 MB/s eta 0:00:14
   --------- ------------------------------ 17.3/70.9 MB 4.0 MB/s eta 0:00:14
   ---------- ----------------------------- 18.1/70.9 MB 4.0 MB/s eta 0:00:14
   ---------- ----------------------------- 18.9/70.9 MB 4.0 MB/s eta 0:00:14
   ----------- ---------------------------- 19.7/70.9 MB 4.0 MB/s eta 0:00:13
   ----------- ---------------------------- 20.4/70.9 MB 4.0 MB/s eta 0:00:13
   ----------- ---------------------------- 21.2/70.9 MB 4.0 MB/s eta 0:00:13
   ------------ --------------------------- 22.0/70.9 MB 4.0 MB/s eta 0:00:13
   ------------- -------------------------- 23.1/70.9 MB 4.0 MB/s eta 0:00:13
   ------------- -------------------------- 23.9/70.9 MB 4.0 MB/s eta 0:00:12
   -------------- ------------------------- 24.9/70.9 MB 4.0 MB/s eta 0:00:12
   -------------- ------------------------- 26.0/70.9 MB 4.1 MB/s eta 0:00:12
   --------------- ------------------------ 27.3/70.9 MB 4.1 MB/s eta 0:00:11
   --------------- ------------------------ 28.3/70.9 MB 4.1 MB/s eta 0:00:11
   ---------------- ----------------------- 29.1/70.9 MB 4.1 MB/s eta 0:00:11
   ---------------- ----------------------- 29.6/70.9 MB 4.1 MB/s eta 0:00:11
   ---------------- ----------------------- 30.1/70.9 MB 4.1 MB/s eta 0:00:11
   ----------------- ---------------------- 30.7/70.9 MB 4.0 MB/s eta 0:00:11
   ----------------- ---------------------- 31.2/70.9 MB 4.0 MB/s eta 0:00:10
   ----------------- ---------------------- 31.7/70.9 MB 4.0 MB/s eta 0:00:10
   ------------------ --------------------- 32.5/70.9 MB 3.9 MB/s eta 0:00:10
   ------------------ --------------------- 33.0/70.9 MB 3.9 MB/s eta 0:00:10
   ------------------- -------------------- 33.8/70.9 MB 3.9 MB/s eta 0:00:10
   ------------------- -------------------- 34.6/70.9 MB 3.9 MB/s eta 0:00:10
   -------------------- ------------------- 35.7/70.9 MB 3.9 MB/s eta 0:00:10
   -------------------- ------------------- 36.4/70.9 MB 3.9 MB/s eta 0:00:09
   --------------------- ------------------ 37.5/70.9 MB 3.9 MB/s eta 0:00:09
   --------------------- ------------------ 38.3/70.9 MB 3.9 MB/s eta 0:00:09
   ---------------------- ----------------- 39.3/70.9 MB 4.0 MB/s eta 0:00:08
   ---------------------- ----------------- 40.4/70.9 MB 4.0 MB/s eta 0:00:08
   ----------------------- ---------------- 41.4/70.9 MB 4.0 MB/s eta 0:00:08
   ------------------------ --------------- 42.7/70.9 MB 4.1 MB/s eta 0:00:07
   ------------------------ --------------- 44.0/70.9 MB 4.1 MB/s eta 0:00:07
   ------------------------- -------------- 45.4/70.9 MB 4.1 MB/s eta 0:00:07
   -------------------------- ------------- 46.7/70.9 MB 4.2 MB/s eta 0:00:06
   --------------------------- ------------ 48.0/70.9 MB 4.2 MB/s eta 0:00:06
   --------------------------- ------------ 48.5/70.9 MB 4.2 MB/s eta 0:00:06
   --------------------------- ------------ 49.3/70.9 MB 4.2 MB/s eta 0:00:06
   ---------------------------- ----------- 50.1/70.9 MB 4.2 MB/s eta 0:00:05
   ---------------------------- ----------- 50.9/70.9 MB 4.2 MB/s eta 0:00:05
   ----------------------------- ---------- 51.9/70.9 MB 4.2 MB/s eta 0:00:05
   ----------------------------- ---------- 52.7/70.9 MB 4.2 MB/s eta 0:00:05
   ------------------------------ --------- 53.5/70.9 MB 4.2 MB/s eta 0:00:05
   ------------------------------ --------- 54.3/70.9 MB 4.2 MB/s eta 0:00:04
   ------------------------------- -------- 55.6/70.9 MB 4.2 MB/s eta 0:00:04
   ------------------------------- -------- 56.6/70.9 MB 4.2 MB/s eta 0:00:04
   -------------------------------- ------- 57.7/70.9 MB 4.2 MB/s eta 0:00:04
   --------------------------------- ------ 59.0/70.9 MB 4.2 MB/s eta 0:00:03
   --------------------------------- ------ 60.0/70.9 MB 4.3 MB/s eta 0:00:03
   --------------------------------- ------ 60.0/70.9 MB 4.3 MB/s eta 0:00:03
   ---------------------------------- ----- 60.6/70.9 MB 4.2 MB/s eta 0:00:03
   ---------------------------------- ----- 61.6/70.9 MB 4.2 MB/s eta 0:00:03
   ----------------------------------- ---- 62.7/70.9 MB 4.2 MB/s eta 0:00:02
   ----------------------------------- ---- 63.7/70.9 MB 4.2 MB/s eta 0:00:02
   ----------------------------------- ---- 63.7/70.9 MB 4.2 MB/s eta 0:00:02
   ------------------------------------ --- 64.0/70.9 MB 4.1 MB/s eta 0:00:02
   ------------------------------------ --- 64.7/70.9 MB 4.1 MB/s eta 0:00:02
   ------------------------------------ --- 65.5/70.9 MB 4.1 MB/s eta 0:00:02
   ------------------------------------- -- 66.3/70.9 MB 4.1 MB/s eta 0:00:02
   ------------------------------------- -- 66.6/70.9 MB 4.1 MB/s eta 0:00:02
   ------------------------------------- -- 66.8/70.9 MB 4.0 MB/s eta 0:00:02
   -------------------------------------- - 67.6/70.9 MB 4.0 MB/s eta 0:00:01
   -------------------------------------- - 68.2/70.9 MB 4.0 MB/s eta 0:00:01
   -------------------------------------- - 68.9/70.9 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------  69.2/70.9 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------  69.7/70.9 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------  70.3/70.9 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------  70.5/70.9 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------  70.8/70.9 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------- 70.9/70.9 MB 3.8 MB/s eta 0:00:00
Installing collected packages: xgboost
Successfully installed xgboost-1.7.5
Note: you may need to restart the kernel to use updated packages.

In [4]:
df = pd.read_csv("diabetes.csv")

In [5]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [6]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [8]:
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [9]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [10]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [11]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [12]:
X = df.drop(["Outcome"],axis= 1).to_numpy()
y = df["Outcome"].to_numpy()

In [5]:
xgb_model = XGBClassifier()

In [14]:
params = {
        'min_child_weight' : [0,1],
        'gamma':[0],
        'subsample' :[0.6,0.7,0.8],
        'colsample_bytree':[0.6,0.8,0.1],
        'max_depth':[3,4,5],
        'learning_rate':[0.03,0.05,0.07,0.09],
        'n_estimators': [400,500,600,700,800],
        'max_delta_step':[0],
        'colsample_bynode':[0,0.5]
    }

In [ ]:
## Grid search and random search are two different methods to find the best params

In [15]:
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV

In [6]:
xgb_model = XGBClassifier()

In [17]:
def timer(start_time = None):
    if not start_time:
        start_time = datetime.now()
        return start_time
    elif start_time:
        thour,temp_sec = divmod((datetime.now() - start_time).total_seconds(),3600)
        tmin,tsec  = divmod(temp_sec,60)
        print('\n Time taken: %i hours %i minutes and %s seconds.' %(thour,tmin,round(tsec,2)))

In [16]:
random_search = RandomizedSearchCV(xgb_model,param_distributions=params,n_iter = 10,scoring = 'roc_auc',n_jobs=10,cv=10,verbose = True)

In [17]:
from datetime import datetime
start_time = timer(None)
random_search.fit(X,y)
timer(start_time)

Fitting 10 folds for each of 10 candidates, totalling 100 fits

C:\Users\pudur\anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[08:47:45] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

 Time taken: 0 hours 0 minutes and 48.14 seconds.

In [18]:
random_search.best_params_

{'subsample': 0.7,
 'n_estimators': 400,
 'min_child_weight': 1,
 'max_depth': 3,
 'max_delta_step': 0,
 'learning_rate': 0.07,
 'gamma': 0,
 'colsample_bytree': 0.8,
 'colsample_bynode': 0}

In [19]:
xgb_model = XGBClassifier(subsample = 0.7,
                         n_estimators = 400,
                         min_child_weight= 1,
                         max_depth = 3,
                         max_delta_step = 0,
                         learning_rate = 0.07,
                         gamma = 0,
                         colsample_bytree = 0.8,
                         colsample_bynode = 0,
                         use_label_encoder=True)

In [20]:
xgb_model

XGBClassifier(base_score=None, booster=None, colsample_bylevel=None,
              colsample_bynode=0, colsample_bytree=0.8,
              enable_categorical=False, gamma=0, gpu_id=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.07, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              n_estimators=400, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, reg_alpha=None,
              reg_lambda=None, scale_pos_weight=None, subsample=0.7,
              tree_method=None, validate_parameters=None, verbosity=None)

In [21]:
xgb_model.fit(X,y)

C:\Users\pudur\anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[08:49:06] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=0, colsample_bytree=0.8,
              enable_categorical=False, gamma=0, gpu_id=-1,
              importance_type=None, interaction_constraints='',
              learning_rate=0.07, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=400, n_jobs=8, num_parallel_tree=1, predictor='auto',
              random_state=0, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
              subsample=0.7, tree_method='exact', validate_parameters=1,
              verbosity=None)

In [22]:
from sklearn.metrics import accuracy_score
y_pred = xgb_model.predict(X)
predictions = [ value for value in y_pred]
accuracy = accuracy_score(y,predictions)
print("Accuracy:%.2f%%" %(accuracy * 100.0))

Accuracy:91.54%

### Train and test

In [ ]:
## complete the train and test

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,shuffle=True)

In [25]:
xgb_model.fit(X_train,y_train)

C:\Users\pudur\anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[08:50:17] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=0, colsample_bytree=0.8,
              enable_categorical=False, gamma=0, gpu_id=-1,
              importance_type=None, interaction_constraints='',
              learning_rate=0.07, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=400, n_jobs=8, num_parallel_tree=1, predictor='auto',
              random_state=0, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
              subsample=0.7, tree_method='exact', validate_parameters=1,
              verbosity=None)

In [26]:
pred_train = xgb_model.predict(X_train)

accuracy_score(y_train,pred_train)

0.9446254071661238

In [27]:
pred_test = xgb_model.predict(X_test)

accuracy_score(y_test,pred_test)

0.6948051948051948

In [28]:
ls

 Volume in drive C has no label.
 Volume Serial Number is E0D4-CD26

 Directory of C:\Users\pudur\codes\codes\files\venkat data science files\venkat data

21-01-2025  08:55    <DIR>          .
21-01-2025  02:27    <DIR>          ..
09-01-2025  08:36    <DIR>          .ipynb_checkpoints
04-11-2024  21:10             3,219 50_Startups_dataset.csv
04-11-2024  21:32           890,259 50_startups_mlr.ipynb
10-10-2023  10:24            51,783 ada_boost_1.ipynb
20-01-2025  08:07            36,992 Adaboost_Classifier.ipynb
06-07-2022  11:18            30,582 Afinn.csv
08-12-2024  11:15           105,159 AI [Regression ].ipynb
30-09-2024  22:52            78,758 ANN Classification model.ipynb
31-05-2023  20:47           119,741 ann_methods_for_classification.ipynb
04-12-2023  08:15            66,432 Anova.ipynb
06-07-2022  11:18            23,666 apple.txt
05-12-2024  22:06           439,891 arima.ipynb
09-04-2023  00:07            50,106 assignment.ipynb
13-01-2025  08:43            88,942 Bagging and Random Forest__bank.ipynb
11-11-2024  22:23            39,044 Bagging classifier and Random Forest on bankruptcy prevention.ipynb
07-07-2024  17:04            93,257 bagging classifier.ipynb
11-11-2024  22:22            63,411 Bagging_Classifier.ipynb
13-01-2025  08:59             7,590 Bagging_Random Forest_Boosting_Stacking.ipynb
15-11-2024  22:21            45,055 bakruptcy file with decision tree.ipynb
10-02-2023  08:22             7,510 bankruptcy-prevention.csv
06-07-2022  11:18           103,983 BEML.csv
09-04-2023  10:09            31,054 Bid_caltrans.txt
06-07-2022  11:18             3,527 Cars.csv
19-05-2024  14:37             2,565 cars_modified.csv
19-05-2024  14:36             7,029 cars_modified.xlsx
20-10-2024  11:24            23,558 cbow and skipgram scratch.ipynb
06-07-2022  11:18                73 checkpoint
01-12-2023  08:32             2,311 chi_2_contingency.ipynb
28-08-2024  20:56             4,563 chi-square.ipynb
06-07-2022  11:18            29,822 claimants (1).csv
07-03-2023  06:32           180,380 climate.txt
07-03-2023  06:34           250,394 climate_results.txt
09-05-2023  08:39         3,730,164 CNN (1).ipynb
09-04-2023  09:42           807,659 connecting database to  python.ipynb
30-09-2022  03:39           448,692 Copy_of_LSTM_Time_Series_Forecasting.ipynb
21-01-2025  08:55            13,949 cv method for adaboost,gradientboost and xgboost.ipynb
15-01-2025  07:14            17,314 cv method for decision tree, bagging, random forest.ipynb
06-07-2022  11:18            67,923 daily-minimum-temperatures (1).csv
06-07-2022  11:18             5,311 data_clean.csv
07-03-2023  08:15         1,010,009 data_results.txt
21-07-2024  12:35             1,104 dataset.csv
30-09-2024  22:16             8,937 datasets.ipynb
27-09-2023  10:41           225,946 Decision Tree.ipynb
13-01-2025  08:34           772,817 Decision Tree_C5.0_CART.ipynb
28-09-2023  11:36           110,956 Decision tree_soccer.ipynb
13-11-2024  20:45             2,666 Decision_Tree,Bagging,Random_forest, cross_validation method.ipynb
28-09-2023  09:39            83,916 Decision_Tree.ipynb
27-09-2023  10:50           296,769 Decision_Tree___.ipynb
26-12-2023  08:43            48,866 Decision_tree_classifier.ipynb
28-11-2022  10:52            32,752 decision_tree_test_soccer.csv
28-11-2022  10:52           185,632 decision_tree_train_soccer.csv
22-12-2023  08:56           930,078 decisiontree2212.ipynb
06-11-2023  08:37            25,884 def functions python.ipynb
06-07-2022  11:18            23,873 diabetes.csv
06-07-2022  11:18         2,993,161 DL2_notes.pdf
15-03-2024  08:47           157,817 doc to vec.ipynb
20-10-2024  13:00           198,523 DOC2VEC.ipynb
06-07-2022  11:18           295,396 DS-11773-Akash Kundu.pdf
15-10-2024  20:09           799,656 ecommerce_sample_data.csv
20-07-2024  17:07           316,712 EDA FULL Fledged PANDAS.ipynb
25-10-2024  21:50         1,407,412 eda part 1.ipynb
25-10-2024  22:10           306,943 eda part 2.ipynb
25-10-2024  20:57           152,064 eda part 3.ipynb
13-09-2023  09:21           170,374 EDA WEEKDAY BATCH COMPLETE PANDAS.ipynb
25-09-2023  10:33         1,468,024 eda_.ipynb
25-10-2023  10:54           571,331 eda___25_10.ipynb
21-12-2023  08:16           124,445 EDA_1.ipynb
08-01-2025  08:07            54,697 EDA_1_Latest (1).ipynb
17-02-2023  09:01            85,128 EDAPart1.ipynb
27-08-2024  21:32           134,172 Feature_Engineering.ipynb
06-07-2022  11:18             9,197 footfalls.csv
21-07-2024  12:37           104,653 Forecasting Model_Arima.ipynb
04-12-2024  22:09         1,372,056 Forecasting_Data Driven Models.ipynb
15-12-2023  12:11         3,651,829 forex_data_for_ml.csv
08-08-2022  16:16            11,336 fun-data.csv
06-07-2022  11:18           107,633 GLAXO.csv
20-01-2025  08:59            84,853 gradient boosting.ipynb
12-10-2023  10:11            59,991 gradient_boost_algo.ipynb
14-07-2024  14:56            24,845 Gradient_Boosting_Classifier.ipynb
24-07-2022  03:16            11,834 h2hteamnewv19.json
17-10-2024  22:09           396,544 Hierarchical Clustering (1).ipynb
25-10-2023  09:39           328,448 hierarchical_clustering part 1.ipynb
18-01-2024  08:11           314,988 hierarchical_clustering_K_means_DBSCAN.ipynb
26-09-2024  20:57            35,008 HousingData.csv
24-10-2024  22:15            17,058 Hypothesis Test.ipynb
01-12-2023  08:35             9,014 hypothesis,two sample, chi-square.ipynb
24-10-2024  21:47             8,581 Hypothesis_testing.ipynb
24-10-2024  21:47             4,958 HypothesisTesting.ipynb
25-11-2022  09:37            14,942 iran_25_players - Sheet1.csv
08-06-2024  17:41            74,154 iris plots.ipynb
11-10-2022  10:08             4,009 IRIS.csv
12-09-2024  20:51               927 iris_logistic_model.pkl
26-10-2023  09:17            31,765 iris_model_pickle.ipynb
07-03-2023  07:55             3,400 Iris_numpy.csv
19-02-2023  13:57             6,619 italy-covid-daywise.csv
17-10-2024  22:34            72,319 Kmeans, DBScan.ipynb
17-10-2024  21:18            40,606 kmeans.ipynb
18-10-2023  10:50            45,412 knn 1.ipynb
21-11-2024  22:25            48,062 KNN.ipynb
30-09-2024  21:17            52,774 knn___.ipynb
16-05-2023  21:04            33,852 Knn_practise.ipynb
10-03-2023  08:30            39,212 KNN_weekday_batch.ipynb
05-10-2023  10:50            81,183 L1,L2, Elastic net weekday batch.ipynb
19-11-2024  22:17            32,623 L1,L2,elastic_net.ipynb
19-11-2024  21:51            84,117 l1_l2__elasticnet_update.ipynb
05-10-2023  11:04            36,769 l1_l2_elastic_net.ipynb
01-04-2023  11:30            20,586 lambda functions.ipynb
14-12-2023  07:50           146,905 linear regression car.ipynb
14-12-2023  07:49            48,468 Linear Regression weekday batch.ipynb
01-06-2024  17:25            93,084 Linear_regression_01_06.ipynb
22-09-2024  12:56               589 Linear_Regression_Model_A.I.ipynb
09-11-2022  10:13         2,890,109 loan-defaulter-risk-analysis-eda.ipynb
19-02-2023  14:19            10,197 locations.csv
09-01-2025  08:36            25,833 Logistic Regression (1).ipynb
31-03-2023  20:39            69,797 Logistic Regression for weekday batch.ipynb
15-11-2024  22:18           102,610 Logistic Regression Project Bankruptcy_final.ipynb
19-12-2023  10:16           106,293 Logistic Regression sample.ipynb
23-06-2024  15:21           118,947 Logistic Regression.ipynb
10-01-2025  07:51           128,370 logistic_code.ipynb
08-11-2024  21:19            85,782 Logistic_Regression_Train_test.ipynb
08-08-2022  16:16            12,089 logisticdrawback.csv
23-02-2024  10:14            52,845 MLP_ANN.ipynb
08-06-2024  16:51         1,226,881 MLR1212.ipynb
03-04-2023  19:40               899 model.pkl
06-07-2022  11:18           234,909 Movie.csv
30-09-2024  22:13         5,024,419 movie_ratings_dataset.csv
06-07-2022  11:18             1,314 mtcars.csv
04-11-2024  21:30           985,110 Multi Linear Regression.ipynb
02-09-2022  02:20           488,776 naive classifier.ipynb
14-12-2022  09:44            61,152 Naive_bayes_Classifier.ipynb
11-03-2024  10:38           257,164 Named Entity Recognition_Emotion Mining_updated.ipynb
15-04-2023  10:37           270,394 NER.ipynb
21-02-2024  09:54           110,282 Neural Network_Back Propagation.ipynb
16-01-2025  09:11         1,469,136 neural networks .ipynb
24-03-2023  07:50           101,374 neural networks weekday.ipynb
04-12-2023  08:32            69,693 neural networks2.ipynb
07-12-2023  10:39           259,330 neuralnetworks for soccer.ipynb
20-02-2023  08:18            21,041 new_covid_data.csv
20-02-2023  08:18            20,524 new_covid_data.xlsx
25-11-2024  21:40            81,968 nlp ml supervised.ipynb
14-03-2024  09:58           317,050 NLP.ipynb
07-03-2024  09:29            70,236 nlp_sup.ipynb
21-07-2024  17:14            27,143 NLP_supervised.ipynb
20-10-2024  10:31            28,324 nlp_unsup.ipynb
06-07-2022  11:18            61,956 NLP-movie-review.csv
22-10-2024  22:18           235,353 Normal Disribution.ipynb
12-08-2024  22:14            58,342 Numpy Operations weekday batch.ipynb
07-12-2024  09:29            88,371 numpy.ipynb
13-08-2024  20:42            63,522 Numpy_operations.ipynb
29-08-2023  14:06           631,283 one_page.pdf
30-01-2023  08:56                20 oops.txt
30-01-2023  08:55                49 oops1.txt
26-05-2024  17:01             6,593 pandas analysis.ipynb
26-05-2024  17:19           141,334 pandas full fledged.ipynb
01-12-2024  12:58           386,724 Pandas Intro1.ipynb
07-08-2024  21:04            71,599 pandas introduction.ipynb
13-09-2023  09:53            70,462 pandas part 1.ipynb
19-05-2024  15:00           209,259 pandas,matplot file.ipynb
24-06-2023  19:25           197,475 pandas_analysis.ipynb
19-05-2024  14:38           128,918 pandas_intro_weekend.ipynb
24-06-2023  19:15           243,388 Pandas_Introduction_Visualisation.ipynb
19-05-2024  17:59           323,404 Pandas_Numpy_Ploting_Introduction.ipynb
08-12-2023  08:35           150,351 pandas_visualisation.ipynb
30-09-2024  20:47           123,438 PCA.ipynb
04-10-2023  11:06            78,596 pca_1.ipynb
15-11-2024  22:25            32,180 PCA_updated_bank.ipynb
29-08-2023  14:12               859 pdf_scanners.ipynb
30-09-2024  22:05            84,339 perceptron.ipynb
06-07-2022  11:18            23,279 pima-indians-diabetes.csv
06-07-2022  11:18            23,279 pima-indians-diabetes.data.csv
06-07-2022  11:18           189,955 Practice.ipynb
06-12-2023  09:06           206,953 Prediction Report with probs and odds matchwise -2023.xlsx
31-03-2023  20:33            29,845 predictions_report.csv
16-12-2024  02:09             7,152 Problematic_accounts_index.xlsx
30-06-2023  10:38             8,904 python _3.ipynb
21-06-2023  23:27            70,596 Python 1 Basics.ipynb
27-06-2023  10:12            76,557 python -2.ipynb
30-06-2023  10:40           270,004 python 4.ipynb
07-07-2023  08:21            12,077 python 6th part def functions.ipynb
02-04-2023  09:57            54,483 python basics.ipynb
09-04-2023  10:21            42,165 python error handling.ipynb
08-04-2023  10:57            13,923 python oops weekend.ipynb
30-01-2023  08:59            16,423 python oops.ipynb
10-03-2023  20:25           101,718 Python part 3.ipynb
15-09-2023  07:43             4,513 Python part2.ipynb
25-01-2023  08:56            23,958 Python seventh part.ipynb
14-09-2023  07:55            62,549 Python Weekend batch.ipynb
12-10-2022  00:34            73,339 Python_learning.ipynb
07-07-2024  17:18            38,736 Random Forest Classifier.ipynb
17-09-2024  21:34           132,141 random_forest_model.pickle
17-09-2024  21:43           136,476 random_forest_model.pkl
15-10-2024  20:10           123,309 Recommendation Engine.ipynb
15-10-2024  22:09            54,888 recommendation_product & user_id.ipynb
06-07-2022  11:18         2,186,682 report.html
19-02-2023  14:21            22,492 results.csv
05-12-2022  10:35            46,259 Ridge_Lasso_ElasticNet.ipynb
26-10-2024  12:45         4,007,480 rnn_lstm_bi_Gru_stacking.ipynb
20-03-2024  16:56            25,948 Roberta_and_Finbert.ipynb
22-09-2024  10:03        24,602,624 Sample.xls
26-10-2024  07:38             5,707 scraping_beautiful soup.ipynb
22-02-2024  14:46           128,123 serie new data.ipynb
22-02-2024  14:34           411,722 serie_newdata.csv
31-10-2024  20:53           115,214 simple linear regression.ipynb
01-06-2024  16:49            99,749 Simple_Linear_Regression.ipynb
11-12-2023  08:38           109,984 simple_linear_regression_1112.ipynb
30-10-2024  21:43            96,394 slr_.ipynb
28-11-2022  10:34           470,516 spain_real_data_modified - sheet1 (1).csv
03-11-2024  09:20            11,052 speech_recognition.ipynb
03-11-2024  03:58                 7 speech_recognition_20241103_035854.txt
03-11-2024  03:59                17 speech_recognition_20241103_035920.txt
03-11-2024  04:01                76 speech_recognition_20241103_040147.txt
03-11-2024  04:03                32 speech_recognition_20241103_040303.txt
03-11-2024  09:15                41 speech_recognition_20241103_091527.txt
03-11-2024  09:16                36 speech_recognition_20241103_091620.txt
03-11-2024  09:17                63 speech_recognition_20241103_091727.txt
05-04-2023  20:15            52,993 sports data spain soccer with the decision tree.ipynb
18-10-2023  09:12            25,057 SVC.ipynb
25-09-2024  21:04            35,890 SVM (1).ipynb
28-11-2024  21:03            34,879 svm 1.ipynb
16-05-2023  20:46            77,578 svm__.ipynb
06-07-2022  11:18             1,688 temp.csv
02-05-2023  20:11            69,065 tennis_adaboost.ipynb
06-04-2023  08:41         5,155,365 Tennis_cleaned_data.csv
09-04-2023  11:34             6,863 tkinter gui.ipynb
06-07-2022  11:18               827 Universities (1).csv
10-11-2023  08:53    <DIR>          Untitled Folder
24-07-2022  03:19             7,568 Untitled.ipynb
12-12-2022  10:37                72 Untitled1.ipynb
17-02-2023  08:41                72 Untitled2.ipynb
01-03-2023  20:40               589 Untitled3.ipynb
29-05-2023  07:07               589 Untitled4.ipynb
19-01-2024  07:51           605,145 USDJPY.csv
21-07-2024  12:35               160 validation.csv
19-05-2024  12:54           617,464 Visualisation Techniques.ipynb
07-12-2024  09:31           103,990 Visualisation.ipynb
25-05-2024  17:18           591,804 visualisation_tech.ipynb
11-12-2023  07:42           950,635 visualisation_tech_0812.ipynb
25-05-2024  18:03           667,235 visualisation_techniques_full.ipynb
22-02-2023  08:56           554,630 Visualisation_WEEK_day_batch.ipynb
07-12-2024  10:04         1,527,119 Visualization_mat_seaborn_Latest.ipynb
06-07-2022  11:18               962 water.csv
06-07-2022  11:18             1,172 wc-at.csv
06-07-2022  11:18           969,007 weather_report.html
16-12-2024  02:10            73,312 webscraping.ipynb
28-02-2023  09:10            76,222 XG_Boost Model Improvement.ipynb
13-12-2022  11:06            43,953 XG_Boost_Classifier.ipynb
21-01-2025  08:51            51,278 xgboost.ipynb
16-10-2023  10:33            61,791 xgboost_1.ipynb
             246 File(s)     93,153,151 bytes
               4 Dir(s)  13,439,606,784 bytes free